"""Configuration management for mt5linux setup."""

from dataclasses import dataclass
from pathlib import Path


@dataclass
class MT5Config:
    """Configuration for an MT5 instance."""

    wine_prefix: Path
    rpyc_port: int
    rpyc_host: str
    venv_path: Path
    project_path: Path

    @classmethod
    def from_env_file(cls, env_file: Path) -> "MT5Config":
        """Load config from .mt5env file."""
        if not env_file.exists():
            raise FileNotFoundError(f"Config file not found: {env_file}")

        config = {}
        with open(env_file) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, value = line.split("=", 1)
                    config[key.strip()] = value.strip().strip('"')

        project_path = env_file.parent
        return cls(
            wine_prefix=Path(config.get("MT5_WINE_PREFIX", project_path / ".mt5")),
            rpyc_port=int(config.get("MT5_RPYC_PORT", 18812)),
            rpyc_host=config.get("MT5_RPYC_HOST", "localhost"),
            venv_path=Path(config.get("MT5_VENV", project_path / ".venv")),
            project_path=project_path,
        )

    def save(self, env_file: Path) -> None:
        """Save config to .mt5env file."""
        content = f'''# MT5 Linux Configuration
# Auto-generated by mt5linux.setup() - edit port here if needed

MT5_WINE_PREFIX="{self.wine_prefix}"
MT5_RPYC_PORT={self.rpyc_port}
MT5_RPYC_HOST="{self.rpyc_host}"
MT5_VENV="{self.venv_path}"
'''
        env_file.write_text(content)


def detect_project_root() -> Path:
    """Detect project root from current directory or caller location."""
    cwd = Path.cwd()

    # Check for common project markers
    markers = [".mt5env", ".mt5", "pyproject.toml", "setup.py", ".git"]
    for marker in markers:
        if (cwd / marker).exists():
            return cwd

    # Default to cwd
    return cwd


def get_config(project_path: Path | None = None) -> MT5Config | None:
    """Get config for project, or None if not configured."""
    project_path = project_path or detect_project_root()
    env_file = project_path / ".mt5env"

    if env_file.exists():
        return MT5Config.from_env_file(env_file)
    return None
